[package]
name = "devmer-providers"
description = "Cloud providers for Devmer IaC"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
devmer-core.workspace = true

async-trait.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
rand.workspace = true
md5 = "0.7"

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "macros"] }
